{% set version = "1.1.29" %}

package:
  name: libxslt
  version: {{ version }}

source:
  fn: libxslt-{{ version }}.tar.gz
  url: ftp://xmlsoft.org/libxml2/libxslt-{{ version }}.tar.gz
  sha256: b5976e3857837e7617b29f2249ebb5eeac34e249208d31f1fbf7a6ba7a4090ce
  patches:
    # https://bugzilla.gnome.org/show_bug.cgi?id=778549
    - 0001-Look-for-libxml2-via-pkg-config-first.patch

build:
  number: 5
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  host:
    - libxml2 2.9.*
    - icu 58.*  # [not win]

  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    # These three can be removed when the patch is dropped.
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - {{ compiler('c') }}

  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14   # [win and py35]
    - libxml2 2.9.*
    - icu 58.*  # [not win]

test:
  commands:
    - xsltproc --version
    - conda inspect linkages -p $PREFIX libxslt  # [not win]
    - conda inspect objects -p $PREFIX libxslt  # [osx]

about:
  home: http://xmlsoft.org/XSLT/
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: http://xmlsoft.org/XSLT/
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
