travis:
  secure:
    BINSTAR_TOKEN: sDdBnv0ufi5ivz5YOBrw5vIpxHiriLCBK14kCccVP4MCr0NQ91/oDgxdIe3CKQOwxBByfwyYro1ukvn1C9DQgRJp8wl6I7YJtEkaFevhh8uOk8vB7FtufXd2fzCytQ4zLguKVnqJ/l40meVxfnQCBuVEQ6zrd5Kz41UJTtz3jX4BT5J8CckDwyACgDdFgp6nv3wPs4IvAWcdgeiNS0HQKbOXdJ0ssBTOmyYsN/HCE3lrJU/bXzYyn0HLAlhyHYjRcCykmppjrZzA3kNAKXhyrEoozBtS16nF+DXcvom1dZUJfuprBWp+CZMW4909Cacd5Zoli2Z9T51ycy7Pg9IAMk/hPCFOAwavyPk4eFuT38mBJoQbJN5+bdDuYnhe3Z559CS6Rc1omP1RHZvYF5qBESXe5eI6GXtq+TGXRuJ4hqpUANGcdiWLp5f0gqOccFgSMpNxG6SVCUUHppaAj0nd/YgaJhejVxtiFpmJe5GC30w5a5QwiVbKtE0T3xJ5/uc7j90XblnRPSfcN7yeXzDRozAopsFuvuywKt8vbxKEzUXRIGuhP56ZkuyhEi37Aoe0IaX8THdkf8s0ca4chuIS+GEn3M+aiA+HdFuyMrVdQhVq7Qi3y5xcBqKoj+cxBTKXBhn3OQf8GuGZC29JZbh8ofYGDQhHdUbcLwkaZCEn19Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
